name: Bug report
description: File a bug report
labels: ["bug"]

body:
  - type: markdown
    attributes: 
      value: |
        Remember to check that your bug hasn't already been reported! 
        Note that specific mod bugs do *not* go here, and go to the appropriate mod's repository.
  - type: input
    id: Needlelight-version
    attributes:
      label: Needlelight Version
      description: "The version of Needlelight you're using"
      placeholder: "v1.14.0.0"
    validations:
      required: true
  - type: input
    id: hk-version
    attributes:
      label: Hollow Knight Version
      description: "The version of Hollow Knight you're using, indicated in the bottom right of the title screen."
      placeholder: "v1.5.78.11833"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: What can someone do to experience the bug you observed?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behaviour
      description: What actually happened?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Errors and Logs
      description: |
        If you still have the error window open (or can reproduce it) please press the copy error button and paste there error here. 
        If you don't, you can attach the log file: `ModInstaller.log` here. You can find logs in `%appdata%\HKModInstaller` on windows and `~/.config/HKModInstaller` on Mac/Linux. There may also be logs in the same folder as the `.exe` or `.app` If there are no logs, please write 'None' here. Note that in any case where the app crashed or indicated an error or exception there *will* be logs you should include located in the previously mentioned folder.
    validations:
      required: true

