blank_issues_enabled: false
contact_links:
  - name: Hollow Knight Modding Discord 
    url: https://discord.gg/VDsg3HmWuB
    about: For support with using Lumafly and other questions/discussions about Hollow Knight Mods
