name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -r win-x64 -p:PublishSingleFile=true -p:Configuration=Release --self-contained true
    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: Scarab-Windows
        path: Scarab/bin/Release/net5.0/win-x64/publish/
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: | 
        cd Scarab
        dotnet publish -r linux-x64 -p:PublishSingleFile=true -p:Configuration=Release --self-contained true
        cd ..
    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: Scarab-Linux
        path: Scarab/bin/Release/net5.0/linux-x64/publish/
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        cd Scarab
        dotnet publish -r osx-x64 -p:PublishSingleFile=true -p:Configuration=Release --self-contained true
        cd ..
        python3 make_app.py Scarab.app Scarab/bin/Release/net5.0/osx-x64/publish
    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: Scarab-MacOS
        path: Scarab.zip
